// <auto-generated>
// This file is generated by LiveCaptureInfoGenerator, do not modify manually
namespace Unity.LiveCapture
{
    class LiveCaptureInfo
    {
        /// <summary>
        /// The name of the package.
        /// </summary>
        public const string Name = "com.unity.live-capture";

        /// <summary>
        /// The display name of the package.
        /// </summary>
        public const string DisplayName = "Live Capture";

        /// <summary>
        /// The version of the package.
        /// </summary>
        public const string Version = "2.0.1";

        /// <summary>
        /// The version used for documentation references.
        /// </summary>
        public const string DocsVersion = "2.0";
    }
}